### ISSUE TITLE
Question regarding the dynamics pre-training

### ISSUE THREAD

**Issue by ssimonc** [polixir/NeoRL#1]
Dear Authors,
I can't get my head around a particular line of code in [pretrain_dynamics.py](https://github.com/polixir/NeoRL/blob/benchmark/benchmark/pretrain_dynamics.py), line 56.
There, the number of hidden units for each hidden layer in the ensemble depends on the task:

```python
    hidden_units = 1024 if config["task"] in ['ib', 'finance', 'citylearn'] else 256
```
Thus, if I understand it correctly, each hidden layer in the 7 models would have 256 units in the Mujoco tasks, 1024 otherwise.
However, the [paper](https://arxiv.org/abs/2102.00714v2) states:

>  ... For model-based approaches, the transition model is represented by a local Gaussian distribution ... ... by an MLP with 4 hidden layers and 256 units per layer ...

On the contrary, following the paper, the algo_init function for [MOPO](https://github.com/polixir/NeoRL/blob/benchmark/benchmark/OfflineRL/offlinerl/algo/modelbase/mopo.py) (as a model-based algorithm example), sets the number of hidden_units in the ensemble to the provided config value, which defaults to 256. Nonetheless, this ensemble is ignored if a pre-trained one is given.
```python
    transition = EnsembleTransition(obs_shape, action_shape, args['hidden_layer_size'], args['transition_layers'], args['transition_init_num']).to(args['device'])
```

All things considered, is there a particular reason why the pretrain_dynamics script instantiates the hidden layers in the ensemble with 1024 units, instead of 256? 
Or can I simply ignore this change, given the fact that the results in the paper, as stated, have been obtained by using the latter value?

Kind regards

**Comment by IcarusWizard** [comment]
Hi, @ssimonc. 

Sorry for your confusion. Recently, we have updated the paper to a new version which can be accessed on [openreview](https://openreview.net/pdf?id=DSo2Zteb9l8) (we haven't uploaded it to arXiv yet). Consider the tasks other than MuJoCo have higher dimensions on both input and output, we increase the hidden size to 1024 to improve the model capacity (the change is stated in line 654 - 656 of the new version).

**Comment by ssimonc** [comment]
Thank you very much for your fast reply! I’d totally missed the newer version of the paper, I’ll check it out as soon as possible.
