### ISSUE TITLE
Expert scores & random scores for normalization

### ISSUE THREAD

**Issue by kwanyoungpark** [polixir/NeoRL#11]
I'm trying to get the normalized score of NeoRL mujoco tasks.
But, I could not find the expert scores & random scores inside the codebase nor in the paper.

Can you provide or guide me where I can get those scores?
(I think there should be somewhere, but I can not find it...)

**Comment by IcarusWizard** [comment]
Please check the [appendix H](https://proceedings.neurips.cc/paper_files/paper/2022/file/9cd828eb8dc81a84fb6bf89a94263e1b-Supplemental-Datasets_and_Benchmarks.zip). The expert returns and the random returns are in the second and fifth columns of each raw result table.

**Comment by kwanyoungpark** [comment]
Thank you for the fast reply!
