### ISSUE TITLE
Baseline Policies and Raw Results

### ISSUE THREAD

**Issue by vkurenkov** [polixir/NeoRL#2]
Hi,

- Do you plan to open-source raw results (especially for the newer version of your paper)? This could be very helpful for computing other relevant metrics.
- Do you plan to open-source baseline policies?

This data could be extremely helpful (considerably decrease needed compute time) for our research.

**Comment by mzktbyjc2016** [comment]
Thanks for your suggestions.

We are planning to open-source the raw scores of the trained policies with corresponding hyper-parameters so that you can compute other metrics. However, these baseline policies take some storage spaces, so we will place them in an open-access disk later.

**Comment by IcarusWizard** [comment]
Hi @vkurenkov. We have released the raw results in `benchmark/results`, feel free to do some analysis!
