### ISSUE TITLE
LSTM

### ISSUE THREAD

**Issue by yosoul93** [polixir/NeoRL#3]
How can this project implement Recurrent Neural Network?

**Comment by mzktbyjc2016** [comment]
Hi, NeoRL is a suite of offline datasets and offline-RL algorithms, so you can also define your own RNN model and use it in the offline-RL algorithms.

By the way, NeoRL has provided a simple RNN (see https://github.com/polixir/NeoRL/blob/2de8f38a246377eb87708d7fa12becf2a5cb850d/benchmark/OfflineRL/offlinerl/utils/net/common.py#L118). 

Hope it helps.
