### ISSUE TITLE
Can I use NeoRL, to generate a dataset, in the d4rl format, e.g for the finance environment?

### ISSUE THREAD

**Issue by krish240574** [polixir/NeoRL#4]
Something similar to what is done here - https://github.com/rail-berkeley/d4rl/blob/master/scripts/generation/generate_ant_maze_datasets.py

I see that the get_dataset() call returns a dict with most of the relevant information for d4l, I wanted to know how I may generate more than the available 10000 data points provided. 

I'd like to use NeoRL, specifically, the finance env and generate a dataset in the d4rl format. That would be highly useful. 

Thanks, 
Krishna

**Comment by IcarusWizard** [comment]
Hi Krishna,

Thanks for your interest in our work. For the finance environment, we provide up to 1000 trajectories of training data, which is roughly 2M transitions. You can change `train_num=1000` in `get_dataset` to get the full dataset. The dataset is already quite large in our sense, but in case you really need to generate more data, use can use the `get_data.py` in our [repo](https://agit.ai/Polixir/OfflineData) to do that. 

To convert our data to d4rl format, you just need to map the keys, e.g. `obs` -> `observations`. Besides, we use `index` to mark the end of each trajectories, you should convert that to `timeouts` in a proper way.

**Comment by krish240574** [comment]
Brilliant, 2M is good enough to get me started, thank you very much ! Cheers, and thanks for the great paper and code !
Krishna
