### ISSUE TITLE
Update Aim version and add Aim running instructions on README

### ISSUE THREAD

**Issue by SGevorg** [polixir/NeoRL#7]
HI, Gev here - the author of [Aim](https://github.com/aimhubio/aim)
Love your work on the NeoRL and would love to contribute.

### Changes Proposal
Aim 3.x has been released a while ago and it's a much improved and better scalable version (especially for the RL cases).
Would love to update Aim to 3.x and add an instruction section on README so it's easier to run the benchmarks?

### Motivation
To provide easy and smoother experience for the NeoRL users with Aim.

**Comment by mzktbyjc2016** [comment]
Thanks for your suggestion!  Currently, we are working on other projects, and will soon update to Aim 3.x if the interface does not change too much.
